### ISSUE TITLE
hide in a single installation

### ISSUE THREAD

**Issue by colomet** [my-language-skills/all-in-one-metadata#187]
If we activate in one single site or if we activate just in one site (or several site but not as a network activation) of a multisite, that tab should not be available in order to avoid mistakes.
![captura de pantalla 2017-10-07 a las 20 29 43](https://user-images.githubusercontent.com/3929177/31310782-74272930-ab9e-11e7-9ce6-848f02e0a346.png)

**Comment by danzhik** [comment]
solved by cahnged design in 0.17
