### ISSUE TITLE
interface design

### ISSUE THREAD

**Issue by colomet** [my-language-skills/all-in-one-metadata#189]
Is complicate to know we have to choose the properties for each type. Now, after the activation, we have acces to a new link, but can be hard to see. 

![captura de pantalla 2017-10-07 a las 20 41 40](https://user-images.githubusercontent.com/3929177/31310864-1c9d0368-aba0-11e7-8a2d-e7852273ca07.png)
![captura de pantalla 2017-10-07 a las 20 41 52](https://user-images.githubusercontent.com/3929177/31310865-1c9e39d6-aba0-11e7-895a-d3edde6f0d13.png)

What if instead of to have the acces to the edition of the properties close to the type, as now, we have a new section where each activate Type let us to see the properties and to do there the activation?
Like a new metabox with all the properties of all the types activated. As now with the types but with the properties.

ask if you do not understand.

**Comment by danzhik** [comment]
redesigned in version 0.18
