### ISSUE TITLE
question

### ISSUE THREAD

**Issue by colomet** [my-language-skills/all-in-one-metadata#190]
too complicate:

what´s that?
![captura de pantalla 2017-10-07 a las 20 39 37](https://user-images.githubusercontent.com/3929177/31310880-804da4d0-aba0-11e7-97b3-dad6928b0c51.png)

I do not understand the meaning of clear and disable. We need to write something or to make something in order to be able to make to uderstand the customers

**Comment by danzhik** [comment]
added info boxes since 0.19
