### ISSUE TITLE
Tab names

### ISSUE THREAD

**Issue by colomet** [my-language-skills/all-in-one-metadata#224]
* [x] I've read and understood the [contribution guidelines](https://github.com/my-language-skills/all-in-one-metadata/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
New tabs name

### Please describe what you expected to happen and why.

Network Metadata in Settings and Site metadata

### Technical info
* WordPress version: 4.9.6
* All in one metadata version: 1.0 dev

**Comment by danzhik** [comment]
solved in 0.19
