### ISSUE TITLE
WebSite schema on header 

### ISSUE THREAD

**Issue by masaka222** [my-language-skills/all-in-one-metadata#42]
Normally we would put the WebSite code in the footer_function as the rest of the code, with an if statement if ( is_home() ). 

![screen shot 2017-05-03 at 15 12 34](https://cloud.githubusercontent.com/assets/23406636/25661995/17c5ad12-3013-11e7-93ee-1756412bb0df.png)

The problem is that in the html of the root page, the </body> and </html> tags are being produced twice so our microdata code is being produced twice too. (wp_footer action is being triggered after the </body> tag)
We need to add the code for the WebSite to a new function that will be called in the header().

**Comment by danzhik** [comment]
solved in following versions
