### ISSUE TITLE
Metadata for general WP sites

### ISSUE THREAD

**Issue by colomet** [my-language-skills/all-in-one-metadata#89]
In order to extend the fuctionality to all the wp sites, we need to integrate inside of some SEO plugin ot at least to make it independet of PB.

**Comment by colomet** [comment]
1. We need to create a settings page, where we could choose wich type works in the installation. We have dozens of Types, is hard and complicate to use it without a first selection of the Type. in that way, we can choose one or two types and then, the number of fields in the place where the authors write the information and the complexity will be lower.
The settings page will follow the http://schema.org/docs/full.html organization. But after each Type we will have 2 chechbox. One for Site level and other for Post level. Then, the administrator can choose wich information go to each place. And how maby types to each place.

**Comment by danzhik** [comment]
follows this workflow since 0.8v
